app = "api-webinar-chat-proxy"
primary_region = "fra"

[build]
  builder = "paketo/buildpacks:node"

[http_service]
  internal_port = 10000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    method = "GET"
    interval = "30s"
    grace_period = "10s"
    path = "/api/health"
    protocol = "http"
    timeout = 5
